# Generated by Django 6.1.1 on 2026-09-08 12:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='child', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_flexible', models.BooleanField(default=True, help_text='If True, the chore is flexible within its weekly or monthly period.')),
                ('specific_day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for weekly chores if not flexible (0=Monday, 6=Sunday).', null=True)),
                ('specific_day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month (1-31) for monthly chores if not flexible.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.familymember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('pending_validation', 'Pending validation'), ('overdue', 'Overdue'), ('validated', 'Validated')], default='to_do', max_length=20)),
                ('was_overdue', models.BooleanField(default=False, help_text='Tracks whether the chore was completed after its due date.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chores.chore')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_occurrences', to='chores.familymember')),
            ],
            options={
                'ordering': ['due_date', 'chore__name'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'due_date'), name='unique_chore_occurrence_per_date')],
            },
        ),
    ]
