apiVersion: v1
kind: Service
metadata:
  name: agent-relay
  labels:
    app: agent-relay
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
      name: http
  selector:
    app: agent-relay
